openapi: 3.1.0
info:
  title: Task Management API
  description: API для управления задачами.
  version: 1.0.1
servers:
  - url: http://localhost:8000/
    description: Локальный сервер
paths:
  /promotions/updatepromotionstatus:
    post:
      summary: обновить статус промо-акции
      requestBody:
        description: обновление промо-акцию
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePromotionStatus'
      responses:
        '200':
          description: статус обновлен
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Promotion'
  /promotions/savepromotion:
    post:
      summary: обновить промо-акцию
      requestBody:
        description: обновление статуса задачи 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePromotion'
      responses:
        '200':
          description: статус обновлен
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Promotion'
  /promotions/deletepromotion:
    delete:
      summary: Удалить задачу по ID
      parameters:
        - name: taskId
          in: path
          required: true
          description: ID задачи
          schema:
            type: string
      responses:
        '204':
          description: Задача успешно удалена
        '404':
          description: Задача не найдена
components:
  schemas:
    Promotion:
      type: object
      properties:
        id:
          type: number
          description: идентификатор акции
        name:
          type: string
          description: название промоакции
        description:
          type: string
          description: описание
        discoutnPercent: 
          type: number
          description: процент скидки
        rowStatusNumber: 
          type: number
          description: цифровой номер статуса записи
        userId":
          type: number
          description: идентификатор пользователя
        CreatedAt:
          type: timestamp
          description: дата создания акции
        UpdatedAt: 
          type: timestamp
          description: дата создания акции
    UpdatePromotionStatus:
      properties:
        id:
          type: number
          description: идентификатор акции{
        newStatusNumber: 
          type: number
          description: цифровой номер статуса записи
    NewPromotion:
      type: object
      properties:
        name:
          type: string
          description: название промоакции
        description:
          type: string
          description: описание
        discoutnPercent: 
          type: number
          description: процент скидки
        rowStatusNumber: 
          type: number
          description: цифровой номер статуса записи
        userId":
          type: number
          description: идентификатор пользователя
    GetPromotions:
      type: object
      properties:
        getParams: 
          type: object
          description: параметры запроса
          properties:
            searchParams:
              type: object
              properties:
                name:
                  type: string
                rowStatusNumber:
                  type: number            
            sortParams:
              type: object
              properties:
                name:
                  type: string
                  enum: ["asc", "desc"]
                rowStatusNumber:
                  type: string
                  enum: ["asc", "desc"]
    UpdatePromotion:
      type: object
      properties:
        id:
          type: number
          description: идентификатор акции
        name:
          type: string
          description: название промоакции
        description:
          type: string
          description: описание
        discoutnPercent:
          type: number
          description: процент скидки
        rowStatusNumber:
          type: number
          description: цифровой номер статуса записи
        userId":
          type: number
          description: идентификатор пользователя
        CreatedAt:
          type: timestamp
          description: дата создания акции
        UpdatedAt:
          type:
          description: дата создания акции
    DeletePromotion:
      type: object
      properties:
        message:
          type: string